### PR TITLE
switch to muon: part 1.5

### PR DESCRIPTION
**Pull request by apprehensions**
libinput and xf86-video-intel need testing.

### CODE REVIEW

**Comment by ehawkvu** [comment]
Looks good so far, I'm testing the packages.

The first issue though is with `gtk+3`, the muon patch depends on the atk removal patches being applied, so that will need to be fixed, along with adding `patch -p1 < 05-muon.patch` be ran with the fribidi removal.

**Comment by wael444** [comment]
> Also the build for libxkbcommon fails if you have valgrind installed.

```
$ kiss s valgrind
ERROR 'valgrind' not found 
```
what is valgrind anyway?

> The first issue though is with gtk+3

```
1 out of 4 hunks FAILED -- saving rejects to file gtk/meson.build.rej
```
is this what you mean?

**Comment by wael444** [comment]
i would also like to point out the last 2 packages that i couldn't convert to muon was `mesa` and `freetype-harfbuzz` - the latter being a muon bug, and mesa being because of LLVM.

**Comment by ehawkvu** [comment]
> > Also the build for libxkbcommon fails if you have valgrind installed.
> 
> ```
> $ kiss s valgrind
> ERROR 'valgrind' not found 
> ```

Here's a link to it: https://github.com/ehawkvu/kiss-personal/tree/master/utils/valgrind


> what is valgrind anyway?

It's a suite of debugging tools - there's a callgraph generator, a memory leak checker, and some other tools.


> > The first issue though is with gtk+3
> 
> ```
> 1 out of 4 hunks FAILED -- saving rejects to file gtk/meson.build.rej
> ```
> 
> is this what you mean?

Yes, that's what I get when running with GNU patch. Busybox patch also fails, but it fails with Hunk 2.

**Comment by eli-schwartz** [comment]
Is it sufficient to leave those packages using Meson for now, and move forward with migrating the packages that have thus far been successfully switched?

**Comment by wael444** [comment]
Yes, since I presume both are muon problems

**Comment by ehawkvu** [comment]
`libxkbcommon` is fixed now, make sure to pull in those changes. That just leaves `gtk+3` to be fixed or left for a later date.

**Comment by wael444** [comment]
btw @eli-schwartz i always wanted to ask, why do i see you specifically in muon-related issues or prs and stuff? dont you like do meson development n stuff

**Comment by wael444** [comment]
also @ehawkvu , am i allowed to update libsigc++ as part of this PR? cairomm will not compile without it. ~~unless #93 takes place and it gets dropped~~

**Comment by eli-schwartz** [comment]
@wael444

Speaking with my Meson core developer hat on, I think it's amazing that muon exists, and I support its development and hang out in the muon development space as well in order to offer advice, insight into Meson design decisions, and the occasional patch to muon's own codebase.

I like to think that meson is a build system description language more than an implementation. The python implementation is really just a reference implementation and a way for me to drive improvements to the language.

That's why I'm also the person that committed updates to Meson's documentation FAQ to teach people about muon existing. The Meson FAQ also speaks about how Meson's language design was specifically intended from the beginning to be implementation language agnostic -- that's why we don't provide a python extension framework, for example.

So really, the better question is, if I'm such a fan of Meson, why *wouldn't* I support muon? Muon vindicates my belief in Meson's core design principles, and makes the meson build system more accessible to people in situations such as bootstrapping, resource constrained systems, etc. :D

**Comment by ehawkvu** [comment]
> also @ehawkvu , am i allowed to update libsigc++ as part of this PR? cairomm will not compile without it. ~unless #93 takes place and it gets dropped~

I'm fine with you updating libsigc++.

**Comment by apprehensions** [comment]
`esources` is a pain in my ass

**Comment by ehawkvu** [comment]
I'm inclined to merge once upstream does the same - many thanks for updating this branch.

**Comment by apprehensions** [comment]
@ehawkvu Is it possible for the rest of the `community` packages to be converted to muon since youre the user of them? Thanks!

**Comment by ehawkvu** [comment]
If you want to restrict this PR's scope to just things outside of community, I'm fine with that - I'm assuming that meson will still be around in some form while we convert the rest of the packages over.

**Pull request closed without merging**
